// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgrmkitnyipxghwhgpho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRncm1raXRueWlweGdod2hncGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwOTYyMjEsImV4cCI6MjA2MDY3MjIyMX0.vXwsZfI6aj8ePpsdzZZNJop3ovNhLTCIZyEnX_s6tnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);